### ISSUE TITLE
Flaw With Static Default Args?

### ISSUE THREAD

**Issue by ldo** [paulross/PythonExtensionPatterns#10]
Looking at your `_parse_args_with_python_defaults` routine defined [here](https://pythonextensionpatterns.readthedocs.io/en/latest/parsing_arguments.html), your `pyObjDefaultArg_0` and `pyObjDefaultArg_1` remain partially allocated even if an exception occurred after they were allocated, but before they were completely initialized. What if the user trapped that exception, let their script continue execution, and then tried calling into your code again? This time it would assume the default objects were fine, and you could end up returning a partially-initialized object. You need to completely free up partially-allocated objects on an exception.

**Comment by paulross** [comment]
Thanks for the observation but I see that is possible for `pyObjDefaultArg_0` but not `pyObjDefaultArg_1`.
