### ISSUE TITLE
Gotos Don’t Nest

### ISSUE THREAD

**Issue by ldo** [paulross/PythonExtensionPatterns#12]
Based on the issues I have raised already, I think your whole `goto`-based approach is flawed. The right way is to adopt an overall structured-programming pattern that looks like this:

    «pointer» = NULL;
    do /*once*/
      {
        ... possible preceding code ...
        allocate «pointer»;
        if («error_occurred»)
            break;
        ... do something with «pointer» ...
      }
    while (false);
    Py_XDECREF(«pointer»);

This kind of structure nests easily and scales to more complex cases, which is vital for dealing with allocation inside loops, for example. (I notice you don’t discuss these.) Avoiding `goto`s helps guarantee that control paths from inner structures cannot avoid going through the cleanup on their way out.

I have a couple of more concrete examples to offer, in the form of Python modules I wrote for my [grainypy](https://github.com/ldo/grainypy) and [dvd_menu_animator](https://github.com/ldo/dvd_menu_animator) projects, which demonstrate this idea in action.

**Comment by paulross** [comment]
Thanks for the suggestion!  You have a perfectly good approach. Obviously I'm quite happy with mine and that is the great thing about code, there are so many different ways to to solve the same problem!

I find my approach scales pretty well by the way.

**Comment by ldo** [comment]
Try applying your approach to [this](https://github.com/ldo/a_structured_discipline_of_programming) example, then.
