### ISSUE TITLE
possible tipo

### ISSUE THREAD

**Issue by niki-sp** [paulross/PythonExtensionPatterns#18]
Introduction: pLast is probably pObj here:

PyObject_Print(pLast, stdout, 0);

**Comment by nybblista** [comment]
I think it was resolved but the update was not reflected on https://pythonextensionpatterns.readthedocs.io/en/latest/refcount.html

**Comment by niki-sp** [comment]
Here too:
`PyObject_Print(pLast, stdout, 0);`

**Comment by paulross** [comment]
Great thanks! My bad. I am about to release version 0.2 of this that includes that fix.
