### ISSUE TITLE
this is a really nice book/tutorial

### ISSUE THREAD

**Issue by 1a1a11a** [paulross/PythonExtensionPatterns#6]
this is a really nice book/tutorial, I read it a few months ago, when I tried to search and read it again today, it is really hard to find it, I think it would be better to have keyword like C extension in the title. Anyway, just some random thoughts. Thank you for the writing.

**Comment by danizen** [comment]
+1

**Comment by christian-korneck** [comment]
+1

thank you!

**Comment by paulross** [comment]
Thanks!
